#!/usr/bin/env bash
#This Bash (init) script manages manage_my_process
PID_file="/var/run/my_process.pid"
if [ "$1" == "start" ]
then
	./manage_my_process &
	echo $$ > $PID_file
	echo "manage_my_process started"
elif [ "$1" == "stop" ]
then
	kill "$(pgrep -f /manage_my_process)"
	rm $PID_file
	echo "manage_my_process stopped"
elif [ "$1" == "restart" ]
then
	kill "$(pgrep -f /manage_my_process)"
	rm $PID_file
	./manage_my_process &
	echo $$ > $PID_file
	echo "manage_my_process restarted"
else
	echo "Usage: manage_my_process {start|stop|restart}"
fi
